In [186]:
#import required libraries
import numpy as np
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [187]:
df = pd.read_csv("C:/Users/HP/Downloads/energydata_complete.csv")
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   date         19735 non-null  object 
 1   Appliances   19735 non-null  int64  
 2   lights       19735 non-null  int64  
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9  

In [125]:
feature_matrix = 'T2'
target_vector = 'T6'
x = df[[feature_matrix]].values
print(x)
y = df[[target_vector]].values
print(y)

[[19.2       ]
 [19.2       ]
 [19.2       ]
 ...
 [25.62857143]
 [25.414     ]
 [25.26428571]]
[[ 7.02666667]
 [ 6.83333333]
 [ 6.56      ]
 ...
 [23.62666667]
 [22.43333333]
 [21.02666667]]


In [126]:
#Instantiate the model
linear_model = LinearRegression()
linear_model.fit(x,y)

LinearRegression()

In [127]:
y_pred = linear_model.predict(x)
y_pred

array([[ 5.37165597],
       [ 5.37165597],
       [ 5.37165597],
       ...,
       [19.67562202],
       [19.19818742],
       [18.86506395]])

In [128]:
rmse = np.sqrt(mean_squared_error(y, y_pred))
round(rmse, 3)

3.644

In [189]:
new_df = df.drop(columns = ["date", "lights"])
print(new_df.head())
#Instantiate MinMaxScaler
scaler = MinMaxScaler()


   Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  45.566667  17.166667  ...  17.033333  45.53  6.600000        733.5    92.0   
1  45.992500  17.166667  ...  17.066667  45.56  6.483333        733.6    92.0   
2  45.890000  17.166667  ...  17.000000  45.50  6.366667        733.7    92.0   
3  45.723333  17.166667  ...  17.000000  45.40  6.250000        733.8    92.0   
4  45.530000  17.200000  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  

In [190]:
feature_matrix = new_df.drop(columns = "Appliances")
# Convert DataFrame to Series
feature_matrix.squeeze()
print(feature_matrix.head())
target_vector = new_df["Appliances"]
target_vector.head()

      T1       RH_1    T2       RH_2     T3       RH_3         T4       RH_4  \
0  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000  45.566667   
1  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000  45.992500   
2  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667  45.890000   
3  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000  45.723333   
4  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000  45.530000   

          T5   RH_5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  17.166667  55.20  ...  17.033333  45.53  6.600000        733.5    92.0   
1  17.166667  55.20  ...  17.066667  45.56  6.483333        733.6    92.0   
2  17.166667  55.09  ...  17.000000  45.50  6.366667        733.7    92.0   
3  17.166667  55.09  ...  17.000000  45.40  6.250000        733.8    92.0   
4  17.200000  55.09  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv

0    60
1    60
2    50
3    50
4    60
Name: Appliances, dtype: int64

In [191]:
x = feature_matrix.values
print(x)
y = target_vector.values
y

[[19.89       47.59666667 19.2        ...  5.3        13.27543316
  13.27543316]
 [19.89       46.69333333 19.2        ...  5.2        18.60619498
  18.60619498]
 [19.89       46.3        19.2        ...  5.1        28.64266817
  28.64266817]
 ...
 [25.5        46.59666667 25.62857143 ... 13.26666667 29.19911708
  29.19911708]
 [25.5        46.99       25.414      ... 13.23333333  6.32278365
   6.32278365]
 [25.5        46.6        25.26428571 ... 13.2        34.11885059
  34.11885059]]


array([ 60,  60,  50, ..., 270, 420, 430], dtype=int64)

In [192]:
#Now we split our dataset into the training and testing dataset.Recall that we had earlier segmented the feature and target 
#variables.
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 42)
print(x_train)


[[21.5        35.62666667 17.79       ... -2.35       36.22667453
  36.22667453]
 [19.5        44.56       18.7        ...  0.96666667 43.19976665
  43.19976665]
 [20.79       35.4        16.89       ... -3.1        24.97605482
  24.97605482]
 ...
 [20.29       35.7        18.2        ... -2.93333333 19.07135808
  19.07135808]
 [21.79       35.56       20.434      ... -4.06666667  1.05059214
   1.05059214]
 [21.32333333 37.73       19.89       ...  4.35       17.45604014
  17.45604014]]


In [134]:
print(y_train)

[ 50  30  40 ...  30  80 130]


In [193]:
#Now we transform x_train using fit_tranform
x_train_trans = scaler.fit_transform(x_train)
x_train_trans

array([[0.49736008, 0.28300439, 0.12284953, ..., 0.19318182, 0.72450918,
        0.72450918],
       [0.28616684, 0.57686404, 0.18899927, ..., 0.34393939, 0.86401848,
        0.86401848],
       [0.42238648, 0.27554825, 0.0574267 , ..., 0.15909091, 0.49942021,
        0.49942021],
       ...,
       [0.36958817, 0.28541667, 0.15265326, ..., 0.16666667, 0.38128609,
        0.38128609],
       [0.5279831 , 0.2808114 , 0.31504725, ..., 0.11515152, 0.02074813,
        0.02074813],
       [0.47870468, 0.35219298, 0.27550279, ..., 0.49772727, 0.34896874,
        0.34896874]])

In [194]:
#Instantiate linear regression
linear_model = LinearRegression()
#fit the model to the training dataset
linear_model.fit(x_train, y_train )
#obtain prediction
y_train_pred = linear_model.predict(x_train_trans)
y_train_pred

array([1.00217047, 1.44946484, 1.20261226, ..., 0.39015235, 1.12680336,
       1.92703279])

In [142]:
mae = mean_absolute_error(y_train, y_train_pred)
round(mae, 3) 

53.742

In [143]:
rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
round(rmse, 3)

95.216

In [144]:
print(x_test)

[[20.89       35.4        17.76       ...  0.         25.6222214
  25.6222214 ]
 [21.89       53.1        21.29       ...  1.2        23.47448458
  23.47448458]
 [21.39       35.5        17.63333333 ... -2.4         0.14336776
   0.14336776]
 ...
 [20.92666667 39.4        18.7        ...  4.78333333 39.63351334
  39.63351334]
 [22.         41.23       20.7        ...  4.9        30.41532108
  30.41532108]
 [20.89       42.29       19.03333333 ...  9.76666667  9.94913896
   9.94913896]]


In [145]:
# Now we tranform x_test using .tranform(), NB: we must use .transform() after we have applied the fit object.
fitted = scaler.fit(x_test)  
x_test_trans = fitted.transform(x_test)
print(x_test_trans)

[[0.43294615 0.22605647 0.12125639 ... 0.29598789 0.51267835 0.51267835]
 [0.53854277 0.71599926 0.37910884 ... 0.35049205 0.46969508 0.46969508]
 [0.48574446 0.22882451 0.1120039  ... 0.18697956 0.00276276 0.00276276]
 ...
 [0.43681802 0.336778   0.18991965 ... 0.51324754 0.79309035 0.79309035]
 [0.55015839 0.38743311 0.33601169 ... 0.51854656 0.60860403 0.60860403]
 [0.43294615 0.41677431 0.21426832 ... 0.73959122 0.19900846 0.19900846]]


In [105]:
print(y_test)

[ 40  90  50 ...  50 110  50]


In [147]:
# obtain prediction
y_test_pred = linear_model.predict(x_test_trans)
y_test_pred

array([ 29.08252491, 216.57555558,  29.73542777, ...,  58.10073354,
        88.38573789,  40.53306402])

In [148]:
mae = mean_absolute_error(y_test, y_test_pred)
round(mae, 3) 

49.093

In [149]:
rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
round(rmse, 3)

97.531

In [151]:
ridge_reg = Ridge(alpha=1.0)
ridge_reg.fit(x_train_trans, y_train)

Ridge()

In [153]:
y_test_pred_r = ridge_reg.predict(x_test_trans)
y_test_pred_r


array([ 30.32993357, 215.16278509,  32.18134883, ...,  60.63295287,
        90.89329948,  46.20793666])

In [154]:
rmse = np.sqrt(mean_squared_error(y_test, y_test_pred_r))
round(rmse, 3)

96.919

In [155]:
lasso_reg = Lasso(alpha = 1.0)
lasso_reg.fit(x_train_trans, y_train)

Lasso()

In [199]:
feat = feature_matrix.columns
features = x_train_trans
print(feat)  

Index(['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5',
       'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out',
       'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1',
       'rv2'],
      dtype='object')


In [200]:
def get_weights_df(model, features, col_name):
    weights = pd.Series(model.coef_, feat).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ["Features", col_name]
    weights_df[col_name].round(3)
    return weights_df

In [202]:
lasso_weights_df = get_weights_df(lasso_reg, x_train_trans, 'Lasso_Weight')
print(lasso_weights_df)
len(lasso_weights_df[lasso_weights_df["Lasso_Weight"]!=0])

       Features  Lasso_Weight
0        RH_out    -50.293976
1          RH_8    -26.102888
2            T1      0.000000
3     Tdewpoint     -0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      5.143148
25         RH_1     56.944516


4

In [157]:
y_test_pred_la = lasso_reg.predict(x_test_trans)
y_test_pred_la
rmse = np.sqrt(mean_squared_error(y_test, y_test_pred_la))
round(rmse, 3)

99.556